### ISSUE TITLE
feat:auto build

### ISSUE THREAD

**Issue by czyt** [novice88/jetbra-server-rust#1]
```
name: Release
on:
  push:
    tags:
      - "*"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Cross build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            exe: jetbra-server
            cross: false

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            exe: jetbra-server
            cross: true

          - os: ubuntu-latest
            target: arm-unknown-linux-musleabi
            exe: jetbra-server
            cross: true

          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
            exe: jetbra-server
            cross: true

          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            exe: jetbra-server
            cross: true

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            exe: jetbra-server.exe
            cross: false

          - os: macos-latest
            target: x86_64-apple-darwin
            exe: jetbra-server
            cross: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Since rust 1.72, some platforms are tier 3
          toolchain: 1.75
          default: true
      
      - name: Install OpenSSL
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install pkg-config libssl-dev
      - name: Install OpenSSL
        if: matrix.os == 'macos-latest'
        run: brew install openssl@3
      
      # Native build
      - name: Install target
        if: matrix.cross == false
        run: rustup target add ${{ matrix.target }}
      - name: Run tests
        if: matrix.cross == false
        run: cargo test --release --target ${{ matrix.target }} --verbose 
      - name: Build release
        if: matrix.cross == false 
        run: cargo build --release --target ${{ matrix.target }}

      # Cross build
      - name: Install cross
        if: matrix.cross
        run: cargo install --version 0.2.5 cross
      - name: Run tests
        if: matrix.cross
        run: cross test --release --target ${{ matrix.target }} --verbose  --no-default-features
      - name: Build release
        if: matrix.cross
        run: cross build --release --target ${{ matrix.target }}  --no-default-features

      - name: Run UPX
        # Upx may not support some platforms. Ignore the errors
        continue-on-error: true
        # Disable upx for mips. See https://github.com/upx/upx/issues/387
        if: matrix.os == 'ubuntu-latest' && !contains(matrix.target, 'mips')
        uses: crazy-max/ghaction-upx@v1
        with:
          version: v4.0.2
          files: target/${{ matrix.target }}/release/${{ matrix.exe }}
          args: -q --best --lzma
      - uses: actions/upload-artifact@v2
        with:
          name: jetbra-server-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.exe }}
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: zip
          filename: jetbra-server-${{ matrix.target }}.zip
          directory: target/${{ matrix.target }}/release/
          path: ${{ matrix.exe }}
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/jetbra-server-${{ matrix.target }}.zip
          generate_release_notes: true
          draft: true
```
我自己的仓库已经测试通过
